urls.py
from django.conf.urls import url, include


urlpatterns = (
    url(r'^web/', include('anansi.web.urls', namespace='anansi-web', app_name='anansi')),
    url(r'^api/', include('anansi.api.urls', namespace='anansi-api', app_name='anansi')),
)

web/urls.py
from django.conf.urls import url
from django.shortcuts import redirect
import views

urlpatterns = (
    url(r'dash/$', views.DashView.as_view(), name='dash'),
    
    url(r'hosts/$', views.HostListView.as_view(), name='host-list'),
    url(r'hosts/create$', views.HostCreateView.as_view(), name='host-create'),
    url(r'host/(?P<pk>[0-9]*)/update$', views.HostUpdateView.as_view(), name='host-update'),
    url(r'host/(?P<pk>[0-9]*)/delete$', views.HostDeleteView.as_view(), name='host-delete'),
    url(r'host/(?P<pk>[0-9]*)/$', views.HostDetailView.as_view(), name='host-detail'),
    
    url(r'groups/$', views.GroupListView.as_view(), name='group-list'),
    url(r'groups/create$', views.GroupCreateView.as_view(), name='group-create'),
    url(r'group/(?P<pk>[0-9]*)/update$', views.GroupUpdateView.as_view(), name='group-update'),
    url(r'group/(?P<pk>[0-9]*)/delete$', views.GroupDeleteView.as_view(), name='group-delete'),
    url(r'group/(?P<pk>[0-9]*)/$', views.GroupDetailView.as_view(), name='group-detail'),
        
    url(r'collectors/$', views.CollectorListView.as_view(), name='collector-list'),
    url(r'collectors/create$', views.CollectorCreateView.as_view(), name='collector-create'),
    url(r'collector/(?P<pk>[0-9]*)/update$', views.CollectorUpdateView.as_view(), name='collector-update'),
    url(r'collector/(?P<pk>[0-9]*)/delete$', views.CollectorDeleteView.as_view(), name='collector-delete'),
    url(r'collector/(?P<pk>[0-9]*)/$', views.CollectorDetailView.as_view(), name='collector-detail'),
    url(r'collector/(?P<slug>[-\w]+)/update$', views.CollectorUpdateView.as_view(), name='collector-update'),
    url(r'collector/(?P<slug>[-\w]+)/delete$', views.CollectorDeleteView.as_view(), name='collector-delete'),
    url(r'collector/(?P<slug>[-\w]+)/$', views.CollectorDetailView.as_view(), name='collector-detail'),

    url(r'libraries/$', views.LibraryListView.as_view(), name='library-list'),
    url(r'libraries/create$', views.LibraryCreateView.as_view(), name='library-create'),
    url(r'library/(?P<pk>[0-9]*)/update$', views.LibraryUpdateView.as_view(), name='library-update'),
    url(r'library/(?P<pk>[0-9]*)/delete$', views.LibraryDeleteView.as_view(), name='library-delete'),
    url(r'library/(?P<pk>[0-9]*)/$', views.LibraryDetailView.as_view(), name='library-detail'),
    
        
    url(r'collectors/$', views.CollectorListView.as_view(), name='collector-list'),
    url(r'collectors/create$', views.CollectorCreateView.as_view(), name='collector-create'),
    url(r'collector/(?P<pk>[0-9]*)/update$', views.CollectorUpdateView.as_view(), name='collector-update'),
    url(r'collector/(?P<pk>[0-9]*)/delete$', views.CollectorDeleteView.as_view(), name='collector-delete'),
    url(r'collector/(?P<pk>[0-9]*)/$', views.CollectorDetailView.as_view(), name='collector-detail'),
            
    url(r'roles/$', views.RoleListView.as_view(), name='role-list'),
    url(r'roles/create$', views.RoleCreateView.as_view(), name='role-create'),
    url(r'role/(?P<pk>[0-9]*)/update$', views.RoleUpdateView.as_view(), name='role-update'),
    url(r'role/(?P<pk>[0-9]*)/delete$', views.RoleDeleteView.as_view(), name='role-delete'),
    url(r'role/(?P<pk>[0-9]*)/$', views.RoleDetailView.as_view(), name='role-detail'),
            
    url(r'books/$', views.BookListView.as_view(), name='book-list'),
    url(r'books/create$', views.BookCreateView.as_view(), name='book-create'),
    url(r'book/(?P<pk>[0-9]*)/update$', views.BookUpdateView.as_view(), name='book-update'),
    url(r'book/(?P<pk>[0-9]*)/delete$', views.BookDeleteView.as_view(), name='book-delete'),
    url(r'book/(?P<pk>[0-9]*)/$', views.BookDetailView.as_view(), name='book-detail'),
)

templates/anansi/base.html
{% extends 'anansi/bootstrap.html' %}

{% load url from future %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block bootstrap3_content %}
    <nav class="navbar navbar-default" id="nav">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'anansi-web:dash' %}">
                    <img id="anansi-logo" src="{% static 'anansi/anansi-logo.png' %}"/></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'anansi-web:dash' %}">Dashboard</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle"
                           data-toggle="dropdown" role="button"
                           aria-expanded="false">Inventory <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'anansi-web:host-list' %}">Hosts</a></li>
                            <li><a href="{% url 'anansi-web:group-list' %}">Groups</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'anansi-web:book-list' %}">Playbooks</a></li>
                            <li><a href="{% url 'anansi-web:role-list' %}">Roles</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Go</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle"
                           data-toggle="dropdown" role="button"
                           aria-expanded="false">Settings <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'anansi-web:collector-list' %}">Collectors</a></li>
                            <li><a href="{% url 'anansi-web:library-list' %}">Libraries</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Logout</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <div class="container" id="main">
        {% bootstrap_messages %}
        <div class="container" id="controls">
            {% block controls %} CONTROLS {% endblock %}
        </div>
        <div class="container" id="content">
            {% block content %} CONTENT {% endblock %}
        </div>
    </div>

{% endblock %}

templates/anansi/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}
{% load staticfiles %}

{% block bootstrap3_extra_head %}
    {{ block.super }}
    {% block anansi_extra_head %}
        <link type="text/css" rel="stylesheet" href="{% static 'anansi/css/anansi.css' %}" />
        <script type="text/javascript" src="{% static 'anansi/js/anansi.js' %}"></script>
        <script type="text/javascript">
            {% block anansi_head_js %}{% endblock %}
        </script>
    {% endblock %}
{% endblock %}
{% block bootstrap3_extra_script %}
    {{ block.super }}
    {% block anansi_tail_js %}{% endblock %}
{% endblock %}

{% block bootstrap3_title %}{% block title %}{% endblock %} | Anansi{% endblock %}

templates/anansi/bootstrap_button_dropdown.html
{% load url from future %}

<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    {{ button_label }} <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
      {% for option in button_options %}
        <li><a href="{% url button_url %}?{{ button_param }}={{ option.0 }}">{{ option.1 }}</a></li>
      {% endfor %}
  </ul>
</div>

templates/anansi/collector_detail.html
{% extends 'anansi/base.html' %}

{% block content %}
something {{ object.id }} {{ object.name }}
{% endblock %}

templates/anansi/collector_list.html
{% extends 'anansi/base.html' %}
{% load url from future %}
{% load anansi_web %}
{% load bootstrap3 %}

{% block title %} Collectors {% endblock %}

{% block controls %}
    {% bootstrap_button_dropdown label="Add Collector" url="anansi-web:collector-create" param="type" options=collector_types %}
{% endblock %}

{% block content %}
<div class="container">
  <h2>Collectors</h2>
  <div class="list-group">
      {% for collector in object_list %}
    <a href="{% url "anansi-web:collector-detail" slug=collector.name %}" class="list-group-item">
      <h4 class="list-group-item-heading">{{ collector.name }} <span class="badge">{{ collector.hosts.count }}</span></h4>
      <p class="list-group-item-text">{{ collector.description }}</p>
    </a>
      {% endfor %}
  </div>
</div>
{% endblock %}

templates/anansi/dash.html
{% extends 'anansi/base.html' %}

{% block title %} Dashboard {% endblock %}

{% block content %}
    dashboard

{% endblock %}

templates/anansi/group_list.html
{% extends 'anansi/base.html' %}

{% block content %}
hosts
{% endblock %}

templates/anansi/host_list.html
{% extends 'anansi/base.html' %}

{% block content %}
hosts
{% endblock %}

templates/anansi/localcollector_detail.html
{% extends 'anansi/collector_detail.html' %}